/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychitieucanhan;

import javax.swing.*;
import entities.*;
import Data.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.plaf.basic.BasicSliderUI;

public class JFrameMain extends javax.swing.JFrame {

    private Timer timer;

    public JFrameMain() {
        initComponents();
        this.setSize(1600, 860);
        timer();

    }

    public void username(String username) {
        this.jLabel2findusername.setText(username);
    }

   

    public void timer() {
        this.timer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Calendar c = java.util.Calendar.getInstance();
                c.setTime(new java.util.Date());
                String data = c.get(java.util.Calendar.DAY_OF_MONTH) + "/" + (c.get(java.util.Calendar.MONTH) + 1) + "/" + c.get(java.util.Calendar.YEAR);
                String t = c.get(java.util.Calendar.HOUR) + " : " + c.get(java.util.Calendar.MINUTE) + " PM";
                jLabel3timer.setText(t);
                jLabel2day.setText(data);
            }
        });

        this.timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4home = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1dailymney = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton2moneyshopping = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton1cashbalance = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton1moneyinves = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2findusername = new javax.swing.JLabel();
        jLabel2day = new javax.swing.JLabel();
        jLabel3timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1logout.setForeground(new java.awt.Color(255, 204, 51));
        jButton1logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/logout_1.png"))); // NOI18N
        jButton1logout.setText("Logout");
        jButton1logout.setFocusable(false);
        jButton1logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1logout);
        jToolBar1.add(jSeparator1);

        jButton4home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4home.setForeground(new java.awt.Color(255, 204, 51));
        jButton4home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/home_house.png"))); // NOI18N
        jButton4home.setText("Home");
        jButton4home.setFocusable(false);
        jButton4home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4homeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4home);
        jToolBar1.add(jSeparator2);

        jButton1dailymney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1dailymney.setForeground(new java.awt.Color(255, 204, 51));
        jButton1dailymney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/bill-icon.png"))); // NOI18N
        jButton1dailymney.setText("Daily Money");
        jButton1dailymney.setFocusable(false);
        jButton1dailymney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1dailymney.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1dailymney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1dailymneyActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1dailymney);
        jToolBar1.add(jSeparator3);

        jButton2moneyshopping.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2moneyshopping.setForeground(new java.awt.Color(255, 204, 51));
        jButton2moneyshopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/images.png"))); // NOI18N
        jButton2moneyshopping.setText("Money Shopping");
        jButton2moneyshopping.setFocusable(false);
        jButton2moneyshopping.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2moneyshopping.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2moneyshopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2moneyshoppingActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2moneyshopping);
        jToolBar1.add(jSeparator4);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/bill-icon.png"))); // NOI18N
        jButton3.setText("income money");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator5);

        jButton1cashbalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1cashbalance.setForeground(new java.awt.Color(255, 204, 51));
        jButton1cashbalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/bill-icon.png"))); // NOI18N
        jButton1cashbalance.setText("Cash balance");
        jButton1cashbalance.setFocusable(false);
        jButton1cashbalance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1cashbalance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1cashbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1cashbalanceActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1cashbalance);
        jToolBar1.add(jSeparator6);

        jButton1moneyinves.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1moneyinves.setForeground(new java.awt.Color(255, 204, 51));
        jButton1moneyinves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/bill-icon.png"))); // NOI18N
        jButton1moneyinves.setText("Money Invested");
        jButton1moneyinves.setFocusable(false);
        jButton1moneyinves.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1moneyinves.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1moneyinves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1moneyinvesActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1moneyinves);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hello :");

        jLabel2findusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2day.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2day.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3timer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3timer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2findusername, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3timer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2day, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2findusername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2day, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel3timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1logoutActionPerformed
        dispose();
        JFrameLogin lo = new JFrameLogin();
        lo.setVisible(true);
    }//GEN-LAST:event_jButton1logoutActionPerformed

    private void jButton4homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4homeActionPerformed
        try {
             JInternalFrameHome jhome = new JInternalFrameHome(this.jLabel2findusername.getText());
        jhome.setVisible(true);

        this.jDesktopPane1.add(jhome);
        jhome.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
      
    }//GEN-LAST:event_jButton4homeActionPerformed

    private void jButton1dailymneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1dailymneyActionPerformed

        try {
              JInternalFramedaidymoney jdaimoney = new JInternalFramedaidymoney(this.jLabel2findusername.getText());
        jdaimoney.setVisible(true);
  
        this.jDesktopPane1.add(jdaimoney);
             jdaimoney.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
      

    }//GEN-LAST:event_jButton1dailymneyActionPerformed

    private void jButton2moneyshoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2moneyshoppingActionPerformed
        try {
                JInternalFrameMoneyShopping jmoney = new JInternalFrameMoneyShopping(this.jLabel2findusername.getText());
        jmoney.setVisible(true);
        this.jDesktopPane1.add(jmoney);
        jmoney.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    
    }//GEN-LAST:event_jButton2moneyshoppingActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        try {
               JInternalFrameIcommoney jimoney = new JInternalFrameIcommoney(this.jLabel2findusername.getText());
       jimoney.setVisible(true);
          this.jDesktopPane1.add(jimoney);
          jimoney.setSelected(true);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
     
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1cashbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1cashbalanceActionPerformed
        try {
              JInternalFramecashbalance jfc = new JInternalFramecashbalance(this.jLabel2findusername.getText());
             jfc.setVisible(true);
             this.jDesktopPane1.add(jfc);
             jfc.setSelected(true);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
   
      
    }//GEN-LAST:event_jButton1cashbalanceActionPerformed

    private void jButton1moneyinvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1moneyinvesActionPerformed
        
        try {
               JInternalFrameMoneyInvested jmi = new JInternalFrameMoneyInvested(this.jLabel2findusername.getText());
          jmi.setVisible(true);
          this.jDesktopPane1.add(jmi);
          jmi.setSelected(true);
        } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_jButton1moneyinvesActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1cashbalance;
    private javax.swing.JButton jButton1dailymney;
    private javax.swing.JButton jButton1logout;
    private javax.swing.JButton jButton1moneyinves;
    private javax.swing.JButton jButton2moneyshopping;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4home;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2day;
    private javax.swing.JLabel jLabel2findusername;
    private javax.swing.JLabel jLabel3timer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
