/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychitieucanhan;

import Cryptography.Valition;
import java.util.*;
import entities.*;
import Data.*;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.*;

public class JInternalFrameMoneyInvested extends javax.swing.JInternalFrame {

    Userdao usdao = new Userdao();
    Valition va = new Valition();
    MoneyInvesdao midao = new MoneyInvesdao();
    Calendar c = Calendar.getInstance();

    public JInternalFrameMoneyInvested(String finsuername) {
        initComponents();

        this.setLocation(5, 98);
        this.setSize(1570, 720);
        this.jLabel9finusername.setVisible(false);
        Users us = usdao.findusername(finsuername);
        this.jLabel9finusername.setText(String.valueOf(us.getUsersid()));
            c.setTime(new Date());
        findtable(midao.findday( Integer.parseInt(this.jLabel9finusername.getText()), (c.get(Calendar.MONTH)+1), c.get(Calendar.YEAR)));
    }
     SimpleDateFormat sdf =  new SimpleDateFormat("yyyy/MM/dd");
    public void findtable(List<MoneyInvesteed> listmi) {
        try {

            DefaultTableModel dfm = new DefaultTableModel();
            dfm.addColumn("Id");
            dfm.addColumn("types of investments");
            dfm.addColumn("Name in vestments");
            dfm.addColumn("Money");
            dfm.addColumn("Date");
            dfm.addColumn("description");

            for (MoneyInvesteed mi : listmi) {
                dfm.addRow(new Object[]{mi.getId(), mi.getTypesofinvestments(), mi.getNameinvestments(), mi.getMoney(), sdf.format(mi.getDate()), mi.getDescription()});
            }
            this.jTable1moneyinves.setModel(dfm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1type = new javax.swing.JComboBox();
        jTextField1namevestment = new javax.swing.JTextField();
        jTextField2money = new javax.swing.JTextField();
        jCalendarCombo1date = new org.freixas.jcalendar.JCalendarCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1descript = new javax.swing.JTextArea();
        jButton1create = new javax.swing.JButton();
        jButton2updates = new javax.swing.JButton();
        jButton3clearn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1moneyinves = new javax.swing.JTable();
        jTextField3search = new javax.swing.JTextField();
        jButton4search = new javax.swing.JButton();
        jButton5delete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2month = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3year = new javax.swing.JComboBox();
        jButton6show = new javax.swing.JButton();
        jLabel9finusername = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("types of investments");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name In Vestments");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Money");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Description ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date");

        jComboBox1type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Input", "Output" }));

        jTextField1namevestment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField2money.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2money.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextArea1descript.setColumns(20);
        jTextArea1descript.setLineWrap(true);
        jTextArea1descript.setRows(5);
        jTextArea1descript.setWrapStyleWord(true);
        jTextArea1descript.setDragEnabled(true);
        jScrollPane1.setViewportView(jTextArea1descript);

        jButton1create.setBackground(new java.awt.Color(204, 153, 255));
        jButton1create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/Creat.png"))); // NOI18N
        jButton1create.setText("Create");
        jButton1create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1createActionPerformed(evt);
            }
        });

        jButton2updates.setBackground(new java.awt.Color(204, 153, 255));
        jButton2updates.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2updates.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/edit.png"))); // NOI18N
        jButton2updates.setText("Updates");
        jButton2updates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2updatesActionPerformed(evt);
            }
        });

        jButton3clearn.setBackground(new java.awt.Color(204, 153, 255));
        jButton3clearn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3clearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/edit-clear.png"))); // NOI18N
        jButton3clearn.setText("Clearn");
        jButton3clearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3clearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCalendarCombo1date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2money, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(jTextField1namevestment)
                                    .addComponent(jComboBox1type, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jButton1create, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2updates, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3clearn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1type, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1namevestment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2money, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCalendarCombo1date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1create, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2updates, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3clearn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Money Invested");

        jTable1moneyinves.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1moneyinves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1moneyinves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1moneyinvesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1moneyinves);

        jTextField3search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3searchKeyPressed(evt);
            }
        });

        jButton4search.setBackground(new java.awt.Color(204, 153, 255));
        jButton4search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/search.png"))); // NOI18N
        jButton4search.setText("Search");
        jButton4search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4searchActionPerformed(evt);
            }
        });

        jButton5delete.setBackground(new java.awt.Color(204, 153, 255));
        jButton5delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/btn_delete.png"))); // NOI18N
        jButton5delete.setText("Delete");
        jButton5delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5deleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Month");

        jComboBox2month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Year");

        jComboBox3year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034" }));

        jButton6show.setBackground(new java.awt.Color(204, 153, 255));
        jButton6show.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6show.setText("Show");
        jButton6show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6showActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Current amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel9finusername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addComponent(jTextField3search, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4search, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(606, 606, 606))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5delete, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2month, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3year, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6show, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9finusername, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3search)
                                .addComponent(jButton4search, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5delete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox2month, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox3year, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6show, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1createActionPerformed
        try {
            String type = String.valueOf(this.jComboBox1type.getSelectedItem());
            String namemoney = this.jTextField1namevestment.getText();
            String money = this.jTextField2money.getText();
            String descipt = this.jTextArea1descript.getText();
            if (namemoney.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Name money empty");
            } else if (money.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Money empty");
            } else if (!va.checmoney(money)) {
                JOptionPane.showMessageDialog(null, "you enter no reasonable money");
            } else if (!namemoney.isEmpty() && !money.isEmpty()) {

                MoneyInvesteed im = new MoneyInvesteed();
                im.setTypesofinvestments(type);
                im.setNameinvestments(namemoney);
                im.setMoney(Long.parseLong(money));
                im.setDate(this.jCalendarCombo1date.getDate());
                im.setDescription(descipt);
                im.getUserid().setUsersid(Integer.parseInt(this.jLabel9finusername.getText()));

                if (midao.create(im)) {
                    JOptionPane.showMessageDialog(null, "successfully created");
                   findtable(midao.findday( Integer.parseInt(this.jLabel9finusername.getText()), (c.get(Calendar.MONTH)+1), c.get(Calendar.YEAR)));
                } else {
                    JOptionPane.showMessageDialog(null, "create failure");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1createActionPerformed

    private void jButton2updatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2updatesActionPerformed
        try {

            int index = this.jTable1moneyinves.getSelectedRow();

            if (index == -1) {
                JOptionPane.showMessageDialog(null, "you choose not to update the line in the table");
            } else {
                String id = this.jTable1moneyinves.getValueAt(index, 0).toString();
                //  Incomemoney imid = imdao.find(Integer.parseInt(id));
                String type = String.valueOf(this.jComboBox1type.getSelectedItem());
                String namemoney = this.jTextField1namevestment.getText();
                String money = this.jTextField2money.getText();
                String descipt = this.jTextArea1descript.getText();
                if (namemoney.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Name money empty");
                } else if (money.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Money empty");
                } else if (!va.checmoney(money)) {
                    JOptionPane.showMessageDialog(null, "you enter no reasonable money");
                } else if (!namemoney.isEmpty() && !money.isEmpty()) {

                    MoneyInvesteed im = new MoneyInvesteed();
                    im.setTypesofinvestments(String.valueOf(this.jComboBox1type.getSelectedItem()));
                    im.setNameinvestments(namemoney);
                    im.setMoney(Long.parseLong(money));
                    im.setDate(this.jCalendarCombo1date.getDate());
                    im.setDescription(descipt);
                    im.getUserid().setUsersid(Integer.parseInt(this.jLabel9finusername.getText()));

                    im.setId(Integer.parseInt(id));
                    if (midao.updates(im)) {
                        JOptionPane.showMessageDialog(null, "successfully Updates");
                      findtable(midao.findday( Integer.parseInt(this.jLabel9finusername.getText()), (c.get(Calendar.MONTH)+1), c.get(Calendar.YEAR)));
                    } else {
                        JOptionPane.showMessageDialog(null, "failure Updates");
                    }

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2updatesActionPerformed

    private void jButton3clearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3clearnActionPerformed
        this.jTextField1namevestment.setText("");
        this.jTextField2money.setText("");
        this.jTextArea1descript.setText("");
    }//GEN-LAST:event_jButton3clearnActionPerformed

    private void jButton5deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5deleteActionPerformed
        int index = this.jTable1moneyinves.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "you choose not to delete the line in the table");
        } else {
            int result = JOptionPane.showConfirmDialog(null, "are you sure", "money Invested delete", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                String id = this.jTable1moneyinves.getValueAt(index, 0).toString();
                if (midao.delete(Integer.parseInt(id))) {
                    JOptionPane.showMessageDialog(null, "successfully delete");
                                findtable(midao.findday( Integer.parseInt(this.jLabel9finusername.getText()), (c.get(Calendar.MONTH)+1), c.get(Calendar.YEAR)));
           
                } else {
                    JOptionPane.showMessageDialog(null, "not delete");
                }

            }
        }
    }//GEN-LAST:event_jButton5deleteActionPerformed

    private void jButton4searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4searchActionPerformed
      
            search();
        

    }//GEN-LAST:event_jButton4searchActionPerformed

    private void jTextField3searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3searchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           
                search();
            
        }
    }//GEN-LAST:event_jTextField3searchKeyPressed

    private void jButton6showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6showActionPerformed
        try {
            String month = String.valueOf(this.jComboBox2month.getSelectedItem());
            String year = String.valueOf(this.jComboBox3year.getSelectedItem());
            int months = Integer.parseInt(month);
            int years = Integer.parseInt(year);

            findtable(midao.findday(Integer.parseInt(this.jLabel9finusername.getText()), months, years));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton6showActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
         JFrametelemoneyinves jf = new JFrametelemoneyinves();
         jf.setVisible(true);
         jf.finusername(this.jLabel9finusername.getText());
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1moneyinvesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1moneyinvesMouseClicked
        try {
            
            int index =  this.jTable1moneyinves.getSelectedRow();
            String id =  this.jTable1moneyinves.getValueAt(index, 0).toString();
            MoneyInvesteed mi = midao.find(Integer.parseInt(id));
            this.jTextField1namevestment.setText(mi.getNameinvestments());
            this.jComboBox1type.setSelectedItem(mi.getTypesofinvestments());
            this.jTextField2money.setText(String.valueOf(mi.getMoney()));
            this.jCalendarCombo1date.setDate(mi.getDate());
            this.jTextArea1descript.setText(mi.getDescription());
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable1moneyinvesMouseClicked

    public void search() {
        DefaultTableModel dtm = (DefaultTableModel) this.jTable1moneyinves.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter sorter = new TableRowSorter(dtm);
        this.jTable1moneyinves.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(this.jTextField3search.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1create;
    private javax.swing.JButton jButton2updates;
    private javax.swing.JButton jButton3clearn;
    private javax.swing.JButton jButton4search;
    private javax.swing.JButton jButton5delete;
    private javax.swing.JButton jButton6show;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1date;
    private javax.swing.JComboBox jComboBox1type;
    private javax.swing.JComboBox jComboBox2month;
    private javax.swing.JComboBox jComboBox3year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9finusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1moneyinves;
    private javax.swing.JTextArea jTextArea1descript;
    private javax.swing.JTextField jTextField1namevestment;
    private javax.swing.JTextField jTextField2money;
    private javax.swing.JTextField jTextField3search;
    // End of variables declaration//GEN-END:variables
}
