/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlychitieucanhan;

import java.util.*;
import javax.swing.*;
import java.security.*;
import entities.*;
import Data.*;
import Cryptography.*;
import java.util.regex.*;

public class Register extends javax.swing.JFrame {

    Users user = new Users();
    Userdao userdao = new Userdao();
    Valition va = new Valition();

passwordEncryption pass = new passwordEncryption();
    public Register() {
        initComponents();
        this.setLocation(900, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1name = new javax.swing.JTextField();
        jTextField2uername = new javax.swing.JTextField();
        jButton1create = new javax.swing.JButton();
        jButton2exit = new javax.swing.JButton();
        jPasswordField1password = new javax.swing.JPasswordField();
        jButton1clearn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register Account");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Account");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/AdminIcon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Data Of Brith");

        jTextField1name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField2uername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1create.setBackground(new java.awt.Color(153, 102, 255));
        jButton1create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/Creat.png"))); // NOI18N
        jButton1create.setText("Create");
        jButton1create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1createActionPerformed(evt);
            }
        });

        jButton2exit.setBackground(new java.awt.Color(153, 102, 255));
        jButton2exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/btn_delete.png"))); // NOI18N
        jButton2exit.setText("Exit");
        jButton2exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2exitActionPerformed(evt);
            }
        });

        jPasswordField1password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1clearn.setBackground(new java.awt.Color(153, 102, 255));
        jButton1clearn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1clearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgaes/edit-clear.png"))); // NOI18N
        jButton1clearn.setText("Clearn");
        jButton1clearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1clearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton1create, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2exit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1clearn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83)
                                .addComponent(jTextField1name, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField1password, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2uername, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2uername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordField1password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1create, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1clearn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1createActionPerformed
        try {

            String name = this.jTextField1name.getText();
            String username = this.jTextField2uername.getText();
            String password = String.valueOf(this.jPasswordField1password.getPassword());

            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(null, "name is empty");
            } else if (username.isEmpty()) {
                JOptionPane.showMessageDialog(null, "username is empty");
            } else if (password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "password is empty");
            } else if (va.checkname(name)) {
                JOptionPane.showMessageDialog(null, "you enter an invalid name (name must not contain special characters)");
            } else if (va.checkusernamepassword(username)) {
                JOptionPane.showMessageDialog(null, "you enter an invalid username (username must not contain special characters and spaces)");
            } else if (va.checkusernamepassword(password)) {
                JOptionPane.showMessageDialog(null, "you enter an invalid password (password must not contain special characters and spaces)");
            } else if (!name.isEmpty() && !username.isEmpty() && !password.isEmpty() && !va.checkname(name) && !va.checkusernamepassword(username) && !va.checkusernamepassword(password)) {

                if (checkusernameagian(username)) {
                    JOptionPane.showMessageDialog(null, "username already exists");
                } else {
                    user.setName(name);
                    user.setUsername(username);
                    user.setPassword(pass.MD5(password));
                    user.setDataofbrith(this.jCalendarCombo1datereg.getDate());
                    if (userdao.create(user)) {
                        JOptionPane.showMessageDialog(null, "created successfully");

                    } else {
                        JOptionPane.showMessageDialog(null, "create failure");
                    }
                }
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }


    }//GEN-LAST:event_jButton1createActionPerformed

    private void jButton1clearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1clearnActionPerformed
        this.jTextField1name.setText("");
        this.jTextField2uername.setText("");
        this.jPasswordField1password.setText("");
    }//GEN-LAST:event_jButton1clearnActionPerformed

    private void jButton2exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2exitActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2exitActionPerformed

    public boolean checkusernameagian(String username) {
        for (Users us : userdao.finllusername()) {
            if (us.getUsername().toUpperCase().equalsIgnoreCase(username.toUpperCase())) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1clearn;
    private javax.swing.JButton jButton1create;
    private javax.swing.JButton jButton2exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1password;
    private javax.swing.JTextField jTextField1name;
    private javax.swing.JTextField jTextField2uername;
    // End of variables declaration//GEN-END:variables
}
